### ISSUE TITLE
Update encapsulation training for CMS

### ISSUE THREAD

**Issue by stvnrlly** [VermontAHS/Vermont-18F-Collaboration#39]
@stvnrlly add a description

**Comment by arouault** [comment]
@stvnrlly add some detail

**Comment by arouault** [comment]
@stvnrlly ping

**Comment by arouault** [comment]
Draft is ready, going to update before presentation. Presentation scheduled for January X.

**Comment by arouault** [comment]
This has been rescheduled for 2/6

**Comment by arouault** [comment]
All set.
