### ISSUE TITLE
Customer Portal Phase 2 Research

### ISSUE THREAD

**Issue by amyashida** [VermontAHS/Vermont-18F-Collaboration#43]
Answer the following questions:

**- What is our goal / what are we trying to accomplish in the next 2 weeks?**
- problem statement is validated by some user research
- positioned as a foundation for roadmap work

**- How will we measure if this is successful (Acceptance Criteria)?**

- [x]  research plan includes programs in both ESD and DVHA
- [x]  research validates or brings to light areas of improvement for the customer portal roadmap
- [x]  research plan outlines who will do the research and the prep process needed
- [x]  script aligns with the goals for the research effort

**- What are the Concrete Next Steps?**
- [x] work with Thani, Bob and Seamus to create a research plan and script for user interviews
- [x] identify who will be doing the research as well as training and travel needed
- [x] ensure plan has approval and buy in from needed parties (Cass, Steering Committee, researchers)

Then: 
- Assign a Lead to this Work
- Add to Project Board in Flight
- Apply any appropriate labels

**Comment by arouault** [comment]
Waiting on comment from Thani, need to schedule time to keep going.

**Comment by arouault** [comment]
Closing
